=== Boukefalos/jlibusb/mcdp/resources/targets/mc68332/registerDictionary.dtd
<?xml version='1.0' encoding='utf-8'?>

<!-- DTD for MC68332 RegisterDictionary.
	Only the type values are MC68332 specific.
-->

<!ELEMENT registerDefinitions ((registerGroup* | register*)*)>
<!ELEMENT registerGroup (register+)>
<!ATTLIST registerGroup
		baseAddress CDATA #REQUIRED>
<!ELEMENT register (description?)>
<!ATTLIST register
		mnemonic CDATA #REQUIRED
		altmnemonic CDATA #IMPLIED
		type (CtrlReg|UserReg|SysReg) #REQUIRED
		value CDATA #REQUIRED
		size (1|2|4) #REQUIRED
		accessmode (supervisor|user|test) #IMPLIED
		accessattr (readonly|writeonly) #IMPLIED>
<!ELEMENT description (#PCDATA)>

=== Boukefalos/jlibusb/mcdp/resources/targets/mc68332/registerDictionary.xml
<?xml version='1.0' encoding='utf-8'?>

<!--  Register Definitions for the Motorola MC68332 Microcontroller  -->
<!DOCTYPE registerDefinitions SYSTEM "registerDictionary.dtd">

<registerDefinitions>
	<!-- data registers -->
	<register mnemonic="D0" type="UserReg" value="0x0" size="4">
		<description>data register 0</description>
	</register>
	<register mnemonic="D1" type="UserReg" value="0x1" size="4">
		<description>data register 1</description>
	</register>
	<register mnemonic="D2" type="UserReg" value="0x2" size="4">
		<description>data register 2</description>
	</register>
	<register mnemonic="D3" type="UserReg" value="3" size="4">
		<description>data register 3</description>
	</register>
	<register mnemonic="D4" type="UserReg" value="4" size="4">
		<description>data register 43</description>
	</register>
	<register mnemonic="D5" type="UserReg" value="5" size="4">
		<description>data register 5</description>
	</register>
	<register mnemonic="D6" type="UserReg" value="6" size="4">
		<description>data register 6</description>
	</register>
	<register mnemonic="D7" type="UserReg" value="7" size="4">
		<description>data register 7</description>
	</register>

	<!-- address registers -->
	<register mnemonic="A0" type="UserReg" value="0x8" size="4">
		<description>address register 0</description>
	</register>
	<register mnemonic="A1" type="UserReg" value="0x9" size="4">
		<description>address register 1</description>
	</register>
	<register mnemonic="A2" type="UserReg" value="0xA" size="4">
		<description>address register 2</description>
	</register>
	<register mnemonic="A3" type="UserReg" value="0xB" size="4">
		<description>address register 3</description>
	</register>
	<register mnemonic="A4" type="UserReg" value="0xC" size="4">
		<description>address register 4</description>
	</register>
	<register mnemonic="A5" type="UserReg" value="0xD" size="4">
		<description>address register 5</description>
	</register>
	<register mnemonic="A6" type="UserReg" value="0xE" size="4">
		<description>address register 06</description>
	</register>
	<register mnemonic="A7" type="UserReg" value="0xF" size="4">
		<description>address register 7</description>
	</register>

	<!-- system registers -->
	<register mnemonic="RPC" type="SysReg" value="0x0" size="4">
		<description>return program counter</description>
	</register>
	<register mnemonic="PCC" type="SysReg" value="0x1" size="4">
		<description>current instruction program counter</description>
	</register>
	<register mnemonic="SR" type="SysReg" value="0xB" size="2">
		<description>status register</description>
	</register>
	<register mnemonic="USP" type="SysReg" value="0xC" size="4">
		<description>user stack pointer (A7)</description>
	</register>
	<register mnemonic="SSP" type="SysReg" value="0xD" size="4">
		<description>supervisor stack pointer</description>
	</register>
	<register mnemonic="SFC" type="SysReg" value="0xE" size="4">
		<description>source function code register</description>
	</register>
	<register mnemonic="DFC" type="SysReg" value="0xF" size="4">
		<description>destination function code register</description>
	</register>
	<register mnemonic="ATEMP" type="SysReg" value="0x8" size="4">
		<description>temporary register A</description>
	</register>
	<register mnemonic="FAR" type="SysReg" value="0x9" size="4">
		<description>fault address register</description>
	</register>
	<register mnemonic="VBR" type="SysReg" value="0xA" size="4">
		<description>vector base register</description>
	</register>

	<registerGroup baseAddress="0xFFFFF000">
		<!-- control registers -->
		<register mnemonic="SIMCR" type="CtrlReg" value="0x0A00"
			size="2">
			<description>sim module configuration register</description>
		</register>
		<register mnemonic="SYNCR" type="CtrlReg" value="0x0A04"
			size="2">
			<description>clock synthesizer control</description>
		</register>
		<register mnemonic="SYPCR" type="CtrlReg" value="0x0A20"
			size="2">
			<description>system protection control</description>
		</register>
		<register mnemonic="CSPAR0" type="CtrlReg" value="0x0A44"
			size="2">
			<description>
				chip select pin assignment register 0
			</description>
		</register>
		<register mnemonic="CSPAR1" type="CtrlReg" value="0x0A46"
			size="2">
			<description>
				chip select pin assignment register 1
			</description>
		</register>
		<register mnemonic="CSBARBT" type="CtrlReg" value="0x0A48"
			size="2">
			<description>CSBOOT base address register</description>
		</register>
		<register mnemonic="CSORBT" type="CtrlReg" value="0x0A4A"
			size="2">
			<description>CSBOOT option register</description>
		</register>

		<register mnemonic="CSBAR0" type="CtrlReg" value="0x0A4C"
			size="2">
			<description>
				chip select 0 base address register
			</description>
		</register>
		<register mnemonic="CSOR0" type="CtrlReg" value="0x0A4E"
			size="2">
			<description>chip select 0 option register</description>
		</register>
		<register mnemonic="CSBAR1" type="CtrlReg" value="0x0A50"
			size="2">
			<description>
				chip select 1 base address register
			</description>
		</register>
		<register mnemonic="CSOR1" type="CtrlReg" value="0x0A52"
			size="2">
			<description>chip select 1 option register</description>
		</register>
		<register mnemonic="CSBAR2" type="CtrlReg" value="0x0A54"
			size="2">
			<description>
				chip select 2 base address register
			</description>
		</register>
		<register mnemonic="CSOR2" type="CtrlReg" value="0x0A56"
			size="2">
			<description>chip select 2 option register</description>
		</register>
		<register mnemonic="CSBAR3" type="CtrlReg" value="0x0A58"
			size="2">
			<description>
				chip select 3 base address register
			</description>
		</register>
		<register mnemonic="CSOR3" type="CtrlReg" value="0x0A5A"
			size="2">
			<description>chip select 3 option register</description>
		</register>
		<register mnemonic="CSBAR4" type="CtrlReg" value="0x0A5C"
			size="2">
			<description>
				chip select 4 base address register
			</description>
		</register>
		<register mnemonic="CSOR4" type="CtrlReg" value="0x0A5E"
			size="2">
			<description>chip select 4 option register</description>
		</register>
		<register mnemonic="CSBAR5" type="CtrlReg" value="0x0A60"
			size="2">
			<description>
				chip select 5 base address register
			</description>
		</register>
		<register mnemonic="CSOR5" type="CtrlReg" value="0x0A62"
			size="2">
			<description>chip select 5 option register</description>
		</register>
		<register mnemonic="CSBAR6" type="CtrlReg" value="0x0A64"
			size="2">
			<description>
				chip select 6 base address register
			</description>
		</register>
		<register mnemonic="CSOR6" type="CtrlReg" value="0x0A66"
			size="2">
			<description>chip select 6 option register</description>
		</register>
		<register mnemonic="CSBAR7" type="CtrlReg" value="0x0A68"
			size="2">
			<description>
				chip select 7 base address register
			</description>
		</register>
		<register mnemonic="CSOR7" type="CtrlReg" value="0x0A6A"
			size="2">
			<description>chip select 7 option register</description>
		</register>
		<register mnemonic="CSBAR8" type="CtrlReg" value="0x0A6C"
			size="2">
			<description>
				chip select 8 base address register
			</description>
		</register>
		<register mnemonic="CSOR8" type="CtrlReg" value="0x0A6E"
			size="2">
			<description>chip select 8 option register</description>
		</register>
		<register mnemonic="CSBAR9" type="CtrlReg" value="0x0A70"
			size="2">
			<description>
				chip select 9 base address register
			</description>
		</register>
		<register mnemonic="CSOR9" type="CtrlReg" value="0x0A72"
			size="2">
			<description>chip select 9 option register</description>
		</register>

		<!-- TPU registers -->
		<!-- adjust the setting of tpumcr to reflect modmap bit -->

		<register mnemonic="TRAMMCR" type="CtrlReg" value="0x0B00"
			size="2">
			<description>
				TPURAM module configuration register
			</description>
		</register>
		<register mnemonic="TRAMBAR" type="CtrlReg" value="0x0B04"
			size="2">
			<description>
				TPURAM base address and status register
			</description>
		</register>

		<register mnemonic="TPUMCR" type="CtrlReg" value="0x0E00"
			size="2">
			<description>TPU module control register</description>
		</register>
		<register mnemonic="TPUCFG" type="CtrlReg" value="0x0E02"
			size="2">
			<description>TPU configuration register</description>
		</register>
		<register mnemonic="DSCR" type="CtrlReg" value="0x0E04"
			size="2">
			<description>
				development support control register
			</description>
		</register>
		<register mnemonic="DSSR" type="CtrlReg" value="0x0E06"
			size="2">
			<description>
				development support status register
			</description>
		</register>
		<register mnemonic="TPUICR" type="CtrlReg" value="0x0E08"
			size="2">
			<description>
				TPU interrupt configuration register
			</description>
		</register>
		<register mnemonic="TPUIER" type="CtrlReg" value="0x0E0A"
			size="2">
			<description>TPU interrupt enable register</description>
		</register>
		<register mnemonic="CFSR0" type="CtrlReg" value="0x0E0C"
			size="2">
			<description>
				channel function select register 0
			</description>
		</register>
		<register mnemonic="CFSR1" type="CtrlReg" value="0x0E0E"
			size="2">
			<description>
				channel function select register 1
			</description>
		</register>
		<register mnemonic="CFSR2" type="CtrlReg" value="0x0E10"
			size="2">
			<description>
				channel function select register 2
			</description>
		</register>
		<register mnemonic="CFSR3" type="CtrlReg" value="0x0E12"
			size="2">
			<description>
				channel function select register 3
			</description>
		</register>
