=== Boukefalos/jlibusb/mcdp/resources/targets/general/device.dtd
<?xml version='1.0' encoding='utf-8'?>

<!-- DTD for memory devices. -->

<!ELEMENT device (attributes, size?, segment+, init?)>
<!ATTLIST device
		type CDATA #REQUIRED
		width (1|2|4) #REQUIRED>
<!ELEMENT segment (attributes?, base, size, subsegment*, subsegmentList?)>
<!ATTLIST segment
		name CDATA #REQUIRED>
<!ELEMENT subsegment  (attributes?, base?, size?, subsegment*)>
<!ATTLIST subsegment
		name CDATA #REQUIRED>
<!ELEMENT subsegmentList (attributes?, size)>
<!ATTLIST subsegmentList
		name CDATA #REQUIRED
		numberOfEntries CDATA #REQUIRED
		startID CDATA #IMPLIED>
<!ELEMENT size (#PCDATA)>
<!ELEMENT base (#PCDATA)>
<!ELEMENT attributes EMPTY>
<!ATTLIST attributes
		mode (replace | change) #IMPLIED
		read (add | remove) #IMPLIED
		write (add | remove) #IMPLIED
		const (add | remove) #IMPLIED
		code (add | remove) #IMPLIED
		var (add | remove) #IMPLIED
		sysconst (add | remove) #IMPLIED
		heap (add | remove) #IMPLIED
		stack (add | remove) #IMPLIED>
<!ELEMENT init (assignment+)>
<!ELEMENT assignment (#PCDATA)>
<!ATTLIST assignment
		 name CDATA #REQUIRED
		 type (value | uri) #REQUIRED>

=== Boukefalos/jlibusb/mcdp/resources/targets/mpc555/devices/deviceAm29LV160D.xml
<?xml version='1.0' encoding='utf-8'?>

<!--  External Flash Description for the Motorola MPC555 Microcontroller  -->
<!DOCTYPE device SYSTEM "../../general/device.dtd">

<device type="Am29LV160D" width="2">
	<attributes mode="change" read="add"></attributes>
	<size>0x200000</size>
	<segment name="ExternalFlash">
		<base>ToppcKernel.CextRomBase</base>
		<size>ToppcKernel.CextRomSize</size>
		<subsegment name="ExcCode">
			<attributes code="add"></attributes>
			<size>ToppcKernel.excpCodeSize</size>
		</subsegment>
		<subsegment name="SysTab">
			<attributes sysconst="add"></attributes>
			<size>0x6000</size>
		</subsegment>
		<subsegment name="S1">
			<attributes const="add" code="add"></attributes>
			<size>0x4000</size>
		</subsegment>
		<subsegment name="S2">
			<size>0x4000</size>
		</subsegment>
		<subsegment name="S3">
			<size>0x10000</size>
		</subsegment>
		<subsegmentList name="S" numberOfEntries="30" startID="4">
			<size>0x20000</size>
		</subsegmentList>
	</segment>
	<init>
		<assignment name="BR0" type="uri">ToppcKernel.pBR0</assignment>
		<assignment name="OR0" type="uri">ToppcKernel.pOR0</assignment>
	</init>
</device>

=== Boukefalos/jlibusb/mcdp/resources/targets/mpc555/devices/deviceRAM.xml
<?xml version='1.0' encoding='utf-8'?>

<!-- RAM description of the Motorola MPC555 Microcontroller  -->
<!DOCTYPE device SYSTEM "../../general/device.dtd">

<device type="RAM" width="4">
	<attributes mode="change" read="add" write="add"></attributes>
	<segment name="InternalFlashAblock0">
		<attributes code="add"></attributes>
		<base>0</base>
		<size>0x2000</size>
		<subsegment name="ExcCode">
			<base>0</base>
		</subsegment>
	</segment>
	<segment name="InternalRAM">
		<base>ToppcKernel.CintRamBase</base>
		<size>ToppcKernel.CintRamSize</size>
		<subsegment name="SysTab">
			<attributes sysconst="add"></attributes>
			<base>ToppcKernel.sysTabAdr</base>
		</subsegment>
		<subsegment name="SegConst">
			<attributes const="add"></attributes>
		</subsegment>
		<subsegment name="SegCode">
			<attributes code="add"></attributes>
		</subsegment>
		<subsegment name="SegVars">
			<attributes var="add"></attributes>
		</subsegment>
		<subsegment name="Stack">
			<attributes stack="add"></attributes>
			<size>ToppcKernel.stackSize</size>
		</subsegment>
	</segment>
	<segment name="ExternalRAM">
		<attributes mode="change"></attributes>
		<base>ToppcKernel.CextRamBase</base>
		<size>ToppcKernel.CextRamSize</size>
		<subsegment name="Heap">
			<attributes heap="add"></attributes>
		</subsegment>
	</segment>
	<init>
		<assignment name="BR0" type="uri">ToppcKernel.pBR0</assignment>
		<assignment name="OR0" type="uri">ToppcKernel.pOR0</assignment>
		<assignment name="BR1" type="uri">ToppcKernel.pBR1</assignment>
		<assignment name="OR1" type="uri">ToppcKernel.pOR1</assignment>
		<assignment name="DMBR" type="uri">
			ToppcKernel.pDMBR
		</assignment>
		<assignment name="DMOR" type="uri">
			ToppcKernel.pDMOR
		</assignment>
		<assignment name="ICTRL" type="value">7</assignment>
		<!-- reset RSR -->
		<assignment name="RSR" type="value">-1</assignment>
		<!-- cause to enter debug mode -->
		<assignment name="DER" type="value">0x31C7400F</assignment>
		<!-- MSR -->
		<assignment name="SRR1" type="value">0x03802</assignment>
	</init>
</device>

=== Boukefalos/jlibusb/mcdp/resources/targets/mpc555/devices/deviceMPC555Flash.xml
<?xml version='1.0' encoding='utf-8'?>

<!--  Internal Flash description for the Motorola MPC555 Microcontroller  -->
<!DOCTYPE device SYSTEM "../../general/device.dtd">

<device type="Ppc555Flash" width="4">
	<attributes mode="replace" read="add"></attributes>
	<segment name="InternalFlashA">
		<base>0x2000</base>
		<size>0x3E000</size>
	</segment>
	<segment name="InternalFlashB">
		<base>0x40000</base>
		<size>0x30000</size>
	</segment>
</device>
